### ISSUE TITLE
Unable to clone submodule.

### ISSUE THREAD

**Issue by MattisLind** [qbarnes/cw2dmk#22]
I tried do the MS-DOS build but it required stuff from the cwsdpmi submodule. Tried to do a git submodule update --init.

But got permission problems.

$ git submodule update --init .
Submodule 'cwsdpmi' (git@github.com:qbarnes/cwsdpmi) registered for path 'cwsdpmi'
Cloning into 'cwsdpmi'...
sign_and_send_pubkey: signing failed: agent refused operation
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:qbarnes/cwsdpmi' into submodule path 'cwsdpmi' failed

When I changed the ./git/config param [ submodule "cwsdpmi"] to use the http path rather than the ssh-path it worked much better and I could retrieve the submodule and build it.

[submodule "cwsdpmi"]
	url = https://github.com/qbarnes/cwsdpmi.git

Please consider changing to https-url for he submodule.

**Comment by qbarnes** [comment]
This is one of those great debates that's been going on since GitHub's epoch.  When cloning a GitHub repo, should you use https or ssh?  Even GitHub the company has gone back and forth on this issue.

Https is simpler for people that just want to check out and look at public repos.  To clone, just use `git` with an https URL and there you go.  After that though, if you want to do any writes to a repo, that's when it gets more complex.  With https cloning you used to be able to type your login and password at a prompt.  Typeable passwords are annoying, can't be safely automated, and are not a just good idea for secure authentication, so GitHub got rid of that feature recently.  Now you have to set up a PAT (personal access token).  Then, if you want to do actions without pasting your PAT every time for authentication, you have to  cache it using a GCM (Git Credential Manager) or use the GitHub CLI (`gh`) which saves it to disk.

On the other hand, using ssh is straight-forward for writing repos.  You set up a public ssh certificate with GitHub and load its private key into an ssh agent just like any other ssh key for logging into hosts.  Then just use the regular `git` command and any other git tools you want, no need to be forced into using `gh` CLI or a GCM.  Coming from the Linux and GitHub Enterprise corporate world, using ssh certs for authentication are second nature.  This is the path I've always chosen since starting with GitHub and any other git repo services since ssh certs are simple, have numerous existing utilities for using and managing them, and are already compatible with most everything.

Unfortunately, there is no way (as far as I know) to make cloning submodules of a GitHub repo compatible with both approaches, https and ssh.  If you know, please let me know.

In the mean time after setting up an ssh cert with GitHub, just clone using the ssh path (`git clone --recursive git@github.com:qbarnes/cw2dmk`) .  If you don't already have an ssh key to use, check out https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.

One thing I have been meaning to do is to create a commit for updating the `BUILDING.md` doc to tell users to use ssh for cloning the repo.  This issue nudges that work higher on the to-do list.

**Comment by MattisLind** [comment]
Interesting. Myself I have mostly been using ssh but then my projects hasn't been involving submodules.  Then there hasn't been any problems. On the other hand cloning others peoples projects I have mostly been using https. As for using SSH vs HTTPS actually in my daytime work we have switched to https since that is the only thing that works reasonably with AWS SSO.

However just adding some docs about this would probably be sufficient.

**Comment by qbarnes** [comment]
I have updated the [BUILDING.md](https://github.com/qbarnes/cw2dmk/blob/master/BUILDING.md) doc to reflect more complete directions.
